### ISSUE TITLE
Different licence for content and code

### ISSUE THREAD

**Issue by benabel** [romulusFR/timeline_informatique#20]
Hi @romulusFR , thanks for sharing this repository, I was just planning to do the same thing when I found your repository on SO. I created a fork of this repository to create a game for high-school students at [terra-numerica.org](https://terra-numerica.org/) during my internship at INRIA. I rewrited the build script in Python. Are you OK if I licence this rewrited code using MIT and using CC-BY SA for tex files based on SO answers.

**Comment by benabel** [comment]
I added detailed licence information for your content and licenced the rewriiten python code under MIT  in order to include legal text standing no warranty(...“AS IS”, WITHOUT WARRANTY OF ANY KIND...). See [README](https://github.com/benabel/timeline_informatique#licences) don't hesitate if you think your licensing is not correctly stated.

**Comment by romulusFR** [comment]
Bonjour, pas de problèmes pour le changement de licence. Ca me fait plaisir que ce soit repris.
Je pensais à reprendre en Python, en fait, des templates Jinja2 ça permettrait peut-être de simplifier la création des cartes, ya pas mal de code avec de la concat de chaines...

Ca ou autre (on a testé les jeu plusieurs fois à la fête de la science), on peut en parler ici ou de vive voix.

**Comment by benabel** [comment]
Bonjour, et merci pour ton retour. Pas mal de concat de chaines c'est vrai... Du coup j'ai déplacé le dépôt sur framasoft pour poursuivre en français 100%: https://framagit.org/terra-numerica/jeux/timeline/.

Merci encore pour le code ouvert.
